### ISSUE TITLE
請問如何建立另一個django+uwsgi並連結同一個nginx container

### ISSUE THREAD

**Issue by nggary** [twtrubiks/docker-django-nginx-uswgi-postgres-tutorial#1]
請問如何建立另一個django+uwsgi並連結同一個nginx container?

**Comment by twtrubiks** [comment]
請問為什麼還要再建立一個呢？  你是要做 Load balance ?

**Comment by nggary** [comment]
因為我希望能夠重用nginx container

**Comment by twtrubiks** [comment]
所以你希望一個nginx container，然後兩個 django+uwsgi，並且 django 是不同的程式？

**Comment by nggary** [comment]
對的

**Comment by twtrubiks** [comment]
好奇問一下，這兩個 django 沒辦法整合成一個嗎？

**Comment by nggary** [comment]
你可以想像成不同的客戶有獨立的django app,所以不能整合

**Comment by twtrubiks** [comment]
了解，這樣的話應該是可以，有空的話我試試看。

**Comment by twtrubiks** [comment]
@nggary  hi~ 我最近剛好看到 haproxy , 
應該可以透過 nginx 的 Access Control List (ACL) 解決你這個問題，
你可以用這個關鍵字下去查查看～  

希望對你有幫助
