### ISSUE TITLE
README.md撰寫指示問題

### ISSUE THREAD

**Issue by Charles5277** [twtrubiks/docker-django-nginx-uswgi-postgres-tutorial#11]
在
'''
python manage.py makemigrations musics
python manage.py migrate
python manage.py createsuperuser
'''
的部分，執行makemigrations時寫的是"musics"
後續指定的範例路徑是/api/music
但我使用/api/music會出現錯誤
使用/api/musics才會正常

**Comment by twtrubiks** [comment]
@Charles5277 謝謝, 感謝提醒, 
的確, `api/musics` 主要是看  [urls.py](https://github.com/twtrubiks/docker-django-nginx-uwsgi-postgres-tutorial/blob/master/api/django_rest_framework_tutorial/urls.py)
```python
......
router = DefaultRouter()
router.register('musics', MusicViewSet)
......
```
可能那時候再測試沒注意到, 文字已修改, 但圖片就沒有改了.
