### ISSUE TITLE
Docker image doesn't change after editing the files inside

### ISSUE THREAD

**Issue by nggary** [twtrubiks/docker-django-nginx-uswgi-postgres-tutorial#2]
I execute "docker-compose up" and the containers are created as expected. However, if I edit the files inside /api folder and execute "docker-compose up" again, the contains remains the same content as before.

I've already try the following command but no luck

docker-compose rm --all 
docker-compose pull 
docker-compose build --no-cache 
docker-compose up -d --force-recreate

**Comment by twtrubiks** [comment]
The easiest way, using "docker-compose down -v",  "-v" = remove volume ( ref. [https://github.com/twtrubiks/docker-tutorial](https://github.com/twtrubiks/docker-tutorial)) and then rebuild.

If you will repeatedly modify the api folder inside things, I suggest you use the volumes path on the host, which is the api folder and your container synchronization, refer to [docker-jenkins-django-tutorial - volumes](https://github.com/twtrubiks/docker-jenkins-django-tutorial#docker--jenkins--django--postgres-%E8%A8%AD%E5%AE%9A) , I introduce two methods of using volumes.

Hope to help you.
