### ISSUE TITLE
docker-compose 中 uwsgi.ini 的路徑

### ISSUE THREAD

**Issue by imgarylai** [twtrubiks/docker-django-nginx-uswgi-postgres-tutorial#6]
在 `docker-compose.yml` 中 `uwsgi.ini` 的路徑是從哪邊做為參考呢？

https://github.com/twtrubiks/docker-django-nginx-uwsgi-postgres-tutorial/blob/079d781dbd23f07debb96fccaf49b0d2a98858a5/docker-compose.yml#L32

我按照你的檔案結構開始了一個新的專案，在執行 `docker-comopse up` 時，出現了這樣的錯誤訊息

```
...
ecp-container | realpath() of uwsgi.ini failed: No such file or directory [core/utils.c line 3643]
ecp-container | realpath() of uwsgi.ini failed: No such file or directory [core/utils.c line 3643]
...
```

而我不管怎麼設定，就是一直找不到 `uwsgi.ini` 這個檔案，所以想請教一下你是否有類似的經驗

**Comment by imgarylai** [comment]
```
docker run -t -i snap /bin/bash
root@c8433f664e1a:/app# ls
Dockerfile  apis  db.sqlite3  db.sqlite3.dev  ecp  home  manage.py  pytest.ini  requirements  requirements.txt  uwsgi.ini  uwsgi_params
root@c8433f664e1a:/app# 
```
看起來檔案是有在 docker image 中的

**Comment by twtrubiks** [comment]
@imgarylai  `uwsgi.ini` 這個檔案是我們自己新增的，
[https://github.com/twtrubiks/docker-django-nginx-uwsgi-postgres-tutorial/blob/master/api/uwsgi.ini](https://github.com/twtrubiks/docker-django-nginx-uwsgi-postgres-tutorial/blob/master/api/uwsgi.ini)，

應該不會找不到 `uwsgi.ini` 才對。

不然可以嘗試把 volumes 清掉， `docker-compose down -v `。
當然有在 docker image 中，這是我們自己build 出來的。

建議可以多認識一下 docker ，可參考 
[Docker 基本教學 - 從無到有 Docker-Beginners-Guide 教你用 Docker 建立 Django + PostgreSQL 📝](https://github.com/twtrubiks/docker-tutorial)

**Comment by imgarylai** [comment]
我後來解決了這個問題

我首先嘗試了 volumen, image ...等，都清掉的情況下重新 build 依然沒有成功

我解決的方式是，原先我是將 volume 和 service 用同樣的命名，例如：
```
services:
  app:
    volumes:
      - app:/app
...
volumes:
  app:
```

之後我把命名改掉後就成功了

**Comment by Dante0713** [comment]
雖然這個問題已經close了, 但是我也有遇到同樣的問題, 而我的解決方式是因為我使用的機器python版本的問題
設備條件：
1. gcp最低階的Compute Engine(全免費型)
2. centos7版本
3. python為centos7自帶python2.7版本

後來我使用這篇[How to Install Python 3.6.4 on CentOS 7](https://www.rosehosting.com/blog/how-to-install-python-3-6-4-on-centos-7/) 的第一種方式升上Python3.6.7版本
之後就成功了

**Comment by twtrubiks** [comment]
@Dante0713 謝謝分享

**Comment by muscletaipei** [comment]
我也發生一樣的問題，但就改一下APP就可以了，但大家的入口網站是什麼呢︖我進不去呢︕會出現
502 Bad Gateway的問題
請問是發生什麼問題嗎︖謝謝。
我目前網頁如下：
https://dworker.tw/
